Add Exercise 8
crytic/building-secure-contracts pull request #160
Opened 2022-11-07 13:54 UTC by lubos-harasta

2022-11-07 13:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/crytic/building-secure-contracts?pullRequest=160) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/crytic/building-secure-contracts?pullRequest=160) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/crytic/building-secure-contracts?pullRequest=160) it.</sub>

2022-11-07 14:28 UTC, anishnaik commented on .vscode/settings.json
> +{
@lubos-harasta can you `git rm` this file from your stage?

2022-11-07 14:34 UTC, anishnaik commented
@lubos-harasta thank you for the submission! I will check this out in the coming days.

2022-11-21 18:10 UTC, glarregay-tob requested changes
This commit deletes files and adds entries to .gitignore.
Can you please delete this commit, keeping only the changes made to Excercise-8.md?

2022-11-23 08:26 UTC, lubos-harasta commented
> This commit deletes files and adds entries to .gitignore. Can you please delete this commit, keeping only the changes made to Excercise-8.md?

@glarregay-tob Done (hopefully in the correct way).

2022-11-23 09:01 UTC, merged